name: CI / CD

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:unit

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results

# You can also add additional steps here, such as deploying your app

